apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myelin-minimal-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - myelinproj.io
    resources:
      - deployers
    verbs:
      - create
      - get
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myelin-minimal
imagePullSecrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myelin-minimal-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myelin-minimal-role
subjects:
  - kind: ServiceAccount
    name: myelin-minimal