allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
mountOptions:
  - vers=4.1
  - noatime
provisioner: cluster.local/myelin-nfs-server-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate