apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployers.myelinproj.io
spec:
  group: myelinproj.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Deployer
    plural: deployers
    shortNames:
      - dp