apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployers.myelin.io
spec:
  group: myelin.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Deployer
    plural: deployers
    shortNames:
      - dp