#This overrides the secret in myelin helm chart, because because the deployer is unable to process forward slash
{{- if .Values.marketplace.authenticateDocker.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
data:
  .dockerconfigjson: {{ tpl ("{\"auths\":{\"https://gcr.io\":{\"auth\":\"{{.Values.marketplace.dockerSecret}}\"}}}") . | b64enc }}
{{- end }}