apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "19388212", "product_id": "myelin", "partner_name": "Myelin"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Myelin
    version: '0.4'
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
  componentKinds:
    - group: batch/v1
      kind: Job
    - group: apps/v1beta2
      kind: Deployment
    - group: v1
      kind: PersistentVolumeClaim
    - group: v1
      kind: Service
  info:
    - name: Myelin Admin Server Address
      type: Reference
      valueFrom:
        serviceRef:
          namespace: {{ .Values.myelin.istioNamespace }}
          name: istio-ingressgateway
          path: myelin-admin-webapp/