applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  marketplace.dockerSecret:
    type: string
    title: Docker Secret
    description: Copy your base64 encoded docker secret

  myelin.artifacts.accesskey:
    type: string
    title: Cloud Storage Access Key
    description: GCP storage access key

  myelin.artifacts.secretkey:
    type: string
    title: Cloud Storage Secret Key
    description: GCP storage secret key

  myelin.adminServer.username:
    type: string
    default: admin@myelin.io
    title: Admin Server User Name

  myelin.adminServer.password:
    type: string
    title: Admin Server Password

  myelin.adminServer.jwtToken:
    type: string
    default: hhTlyHXBG5imq32C
    title: Admin Server JWT Token

  adminServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-admin-server:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.adminServer.apiServer.imageName
            tag: myelin.imageVersion

  adminServerWebappImage:
    type: string
    default: gcr.io/myelin-public/myelin:v0.1.7
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.adminServer.webappServer.imageName
            tag: myelin.adminServer.webappServer.imageVersion

  axonControllerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-axon-controller:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.axonController.imageName
            tag: myelin.imageVersion

  deployerControllerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-deployer-controller:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.deployerController.imageName
            tag: myelin.imageVersion

  metricServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-metric-server:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.metricServer.imageName
            tag: myelin.imageVersion

  triggerServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-trigger-server:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.triggerServer.imageName
            tag: myelin.imageVersion

  deployerProxyImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-deployer-proxy:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.deployerProxy.imageName
            tag: myelin.imageVersion

  executorImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-exec:v0.4.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.executorImage.imageName
            tag: myelin.imageVersion

  myelin.serviceAccount.name:
    type: string
    title: Myelin App Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: myelin-app-role

  myelin.prometheus-op.prometheusOperator.serviceAccount.name:
    type: string
    title: Prometheus Operator Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: prometheus-operator-myelin-role

  myelin.nfs-server.rbac.serviceAccountName:
    type: string
    title: NFS Server Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: myelin-nfs-provisioner

required:
  - name
  - namespace
  - marketplace.dockerSecret
  - myelin.artifacts.accesskey
  - myelin.artifacts.secretkey
  - myelin.adminServer.password
x-google-marketplace:
  clusterConstraints:
    istio:
      type: REQUIRED