applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  adminServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-admin-server:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.adminServer.imageName
            tag: myelin.imageVersion

  adminServerWebappImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-admin-webapp:v0.1.5-20190602195657
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.adminServer.webappServer.ImageName
            tag: myelin.adminServer.webappServer.ImageVersion

  axonControllerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-axon-controller:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.axonController.imageName
            tag: myelin.imageVersion

  deployerControllerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-deployer-controller:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.deployerController.imageName
            tag: myelin.imageVersion

  metricServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-metric-server:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.metricServer.imageName
            tag: myelin.imageVersion

  triggerServerImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-trigger-server:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.triggerServer.imageName
            tag: myelin.imageVersion

  deployerProxyImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-deployer-proxy:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.deployerProxy.imageName
            tag: myelin.imageVersion

  executorImage:
    type: string
    default: gcr.io/myelin-public/myelin/myelin-exec:v0.3.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: myelin.repository #gcr.io
            repo: myelin.executorImage.imageName
            tag: myelin.imageVersion

  myelin.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: myelin-app-role

  myelin.prometheus-op.prometheusOperator.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: prometheus-operator-myelin-role

  myelin.nfs-server.rbac.serviceAccountName:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: myelin-nfs-provisioner

required:
- name
- namespace
