#https://github.com/helm/helm/issues/4490
istio:
  enabled: false
  createCustomResource: false

myelin-crd:
  enabled: false

rook-ceph:
  enabled: false

global:
  rbac:
    create: false

myelin:
  serviceAccount:
    create: false
  nfs-server:
    rbac:
      create: false
    storageClass:
      create: false
      provisionerName: cluster.local/myelin-nfs-server-provisioner
  prometheus-op:
    kubeScheduler:
      enabled: false
    rbac:
      create: false
    prometheusOperator:
      createCustomResource: false
  rook-ceph:
    enabled: false
    agent:
      flexVolumeDirPath: /home/kubernetes/flexvolume
  axonController:
    dockerServer: gcr.io
    dockerNamespace: myelin-public/myelin-images
    config:
      artifactRepository:
        archiveLogs: true
        s3:
          bucket: myelin-dev
          endpoint: storage.googleapis.com
          region: eu-west-1
          accessKeySecret:
            name: myelin-artifacts
            key: accesskey
          secretKeySecret:
            name: myelin-artifacts
            key: secretkey
  deployerController:
    config:
      artifactRepository:
        archiveLogs: true
        s3:
          bucket: myelin-dev
          endpoint: storage.googleapis.com
          region: eu-west-1
          accessKeySecret:
            name: myelin-artifacts
            key: accesskey
          secretKeySecret:
            name: myelin-artifacts
            key: secretkey
  dockerSecret:
    auths:
      https://gcr.io:
        auth:
  artifacts:
    accesskey:
    secretkey:
  github:
    sshPrivateKey:
    sshPublicKey: